// Ba ngon ngu: Viet, Anh, Trung. Tach rieng ra file de them ngon ngu moi chi
// phai sua mot cho, va de nguoi khac dong gop ban dich ma khong dung vao ma UI.
const NGON_NGU = {
  vi: {
    bi_an:'Quân bị ăn', giai_thich_muc:'Thời gian máy nghĩ mỗi nước',
    khong_co:'chưa ăn quân nào',
    ten:'Tiếng Việt', tieu_de:'Bàn phân tích', phu:'thang 0–1000 cho Đỏ',
    can_bang:'Cân bằng', do_loi:'Đỏ ưu thế', den_loi:'Đen ưu thế',
    do_thang:'Đỏ thắng', den_thang:'Đen thắng',
    nuoc_tot:'Nước tốt nhất cho', bien_chinh:'biến chính',
    neu_di:'nếu đi', diem_thanh:'điểm thành', nuoc_vua_di:'Nước vừa đi',
    theo_sach:'Theo sách', luong_gia:'lượng giá', tinh:'tĩnh', sau:'sâu',
    do_sau:'độ sâu', so_nut:'số nút', thoi_gian:'thời gian', nut_giay:'nút/s',
    may:'Máy', muc_do:'Mức độ', ben_cam:'Bạn cầm',
    de:'Dễ — 0,5 giây', vua:'Vừa — 3 giây', kho:'Khó — 10 giây',
    do:'Đỏ (đi trước)', den:'Đen (đi sau)',
    choi_may:'Chơi với máy', tu_choi:'Tự chơi hai bên',
    lui:'Lùi', van_moi:'Ván mới', xoay:'Xoay', di_goi_y:'Đi nước gợi ý',
    nap_fen:'Nạp FEN', nuoc_da_di:'Nước đã đi',
    den_luot:'Đến lượt bạn', may_nghi:'Máy đang nghĩ…',
    dang_phan_tich:'Đang phân tích…', bi_chieu:'đang bị chiếu!',
    ban_thang:'Bạn thắng!', may_thang:'Máy thắng', hoa:'Hoà',
    tot:'Tốt', khong_chuan:'Không chuẩn', sai_lam:'Sai lầm',
    sai_nghiem:'Sai nghiêm trọng', chat_luong:'Nước vừa đi',
    chia_se:'Máy khác vào bằng', luot_cua:'Đến lượt',
  },
  en: {
    bi_an:'Captured', giai_thich_muc:'Thinking time per move',
    khong_co:'none captured yet',
    ten:'English', tieu_de:'Analysis board', phu:'0–1000 scale for Red',
    can_bang:'Balanced', do_loi:'Red is better', den_loi:'Black is better',
    do_thang:'Red wins', den_thang:'Black wins',
    nuoc_tot:'Best move for', bien_chinh:'main line',
    neu_di:'if played', diem_thanh:'score becomes', nuoc_vua_di:'Last move',
    theo_sach:'From book', luong_gia:'evaluator', tinh:'static', sau:'deep',
    do_sau:'depth', so_nut:'nodes', thoi_gian:'time', nut_giay:'nodes/s',
    may:'Engine', muc_do:'Level', ben_cam:'You play',
    de:'Easy — 0.5 s', vua:'Normal — 3 s', kho:'Hard — 10 s',
    do:'Red (first)', den:'Black (second)',
    choi_may:'Play the engine', tu_choi:'Play both sides',
    lui:'Undo', van_moi:'New game', xoay:'Flip', di_goi_y:'Play best move',
    nap_fen:'Load FEN', nuoc_da_di:'Moves',
    den_luot:'Your turn', may_nghi:'Engine thinking…',
    dang_phan_tich:'Analysing…', bi_chieu:'in check!',
    ban_thang:'You win!', may_thang:'Engine wins', hoa:'Draw',
    tot:'Good', khong_chuan:'Inaccuracy', sai_lam:'Mistake',
    sai_nghiem:'Blunder', chat_luong:'Last move',
    chia_se:'Other devices', luot_cua:'Turn',
  },
  zh: {
    bi_an:'被吃棋子', giai_thich_muc:'每步思考时间',
    khong_co:'尚未吃子',
    ten:'中文', tieu_de:'分析板', phu:'红方 0–1000 分制',
    can_bang:'均势', do_loi:'红方优势', den_loi:'黑方优势',
    do_thang:'红方胜', den_thang:'黑方胜',
    nuoc_tot:'最佳着法', bien_chinh:'主要变例',
    neu_di:'若走', diem_thanh:'分数变为', nuoc_vua_di:'上一着',
    theo_sach:'来自开局库', luong_gia:'评估', tinh:'静态', sau:'深层',
    do_sau:'深度', so_nut:'节点', thoi_gian:'用时', nut_giay:'节点/秒',
    may:'引擎', muc_do:'难度', ben_cam:'你执',
    de:'简单 — 0.5 秒', vua:'普通 — 3 秒', kho:'困难 — 10 秒',
    do:'红方（先行）', den:'黑方（后行）',
    choi_may:'人机对弈', tu_choi:'双方自走',
    lui:'悔棋', van_moi:'新局', xoay:'翻转', di_goi_y:'走最佳着',
    nap_fen:'载入 FEN', nuoc_da_di:'着法',
    den_luot:'轮到你', may_nghi:'引擎思考中…',
    dang_phan_tich:'分析中…', bi_chieu:'被将军！',
    ban_thang:'你赢了！', may_thang:'引擎获胜', hoa:'和棋',
    tot:'好棋', khong_chuan:'不精确', sai_lam:'失误',
    sai_nghiem:'严重失误', chat_luong:'上一着',
    chia_se:'其他设备', luot_cua:'轮到',
  },
};
