// Ba ngon ngu: Viet, Anh, Trung. Tach rieng ra file de them ngon ngu moi chi
// phai sua mot cho, va de nguoi khac dong gop ban dich ma khong dung vao ma UI.
const NGON_NGU = {
  vi: {
    mui_ten:'Mũi tên', bat:'bật', tat:'tắt',
    cach_ghi:'Cách ghi nước đi', vd:'Ví dụ',
    g_tan:'tấn', g_thoai:'thoái', g_binh:'bình',
    g_tan_t:'Tiến về phía đối phương. Số đi sau là SỐ BƯỚC (quân đi thẳng) hoặc CỘT ĐÍCH (Mã, Tượng, Sĩ).',
    g_thoai_t:'Lùi về phía mình. Cách ghi số giống tấn.',
    g_binh_t:'Đi ngang. Số đi sau luôn là CỘT ĐÍCH.',
    g_cot:'Cột đánh số từ phía bên đi nhìn sang: Đỏ đếm từ phải sang trái, Đen đếm từ trái sang phải. Nên cùng một cột có hai số khác nhau tuỳ bên.',
    vd1:'Pháo 2 bình 5 — Pháo ở cột 2 đi ngang sang cột 5',
    vd2:'Mã 8 tấn 7 — Mã ở cột 8 tiến lên, tới cột 7',
    vd3:'Xe 1 thoái 2 — Xe ở cột 1 lùi 2 bước',
    do_:'Đỏ', den_:'Đen', chua_di:'chưa đi',
    l6:'Sĩ và Tướng không được rời cung 9 ô ở giữa hàng cuối.',
    l7:'Tốt chưa qua sông chỉ tiến thẳng, không đi ngang và không lùi.',
    l8:'Pháo di chuyển như Xe nhưng ăn quân thì bắt buộc phải có đúng một quân làm ngòi ở giữa.',
    l9:'Không có nhập thành, không có bắt tốt qua đường, không có phong cấp như cờ vua.',
    goi_y:'Gợi ý nước đi', ky_hieu:'chữ trên quân', ghi_nuoc:'ghi nước đi', ten_quan:'Tên quân',
    luat:'Luật chơi', cach_di:'Cách đi quân', luat_dac_biet:'Luật đặc biệt',
    quan:'Quân', di_the_nao:'Đi thế nào',
    q_K:'Đi ngang dọc 1 ô, chỉ trong cung 9 ô. Không được đối mặt tướng địch qua cột trống.',
    q_A:'Đi chéo 1 ô, chỉ trong cung 9 ô. Luôn ở cạnh tướng để che chắn.',
    q_E:'Đi chéo 2 ô. KHÔNG qua sông. Bị chặn nếu ô giữa có quân (cản mắt).',
    q_H:'Đi 1 ngang 2 dọc hoặc 2 ngang 1 dọc. Bị chặn nếu ô kề theo hướng dài có quân (cản chân).',
    q_R:'Đi ngang dọc bao nhiêu ô cũng được, miễn không có quân chắn.',
    q_C:'Đi như xe. Nhưng ĂN thì phải nhảy qua ĐÚNG MỘT quân làm ngòi.',
    q_P:'Tiến 1 ô. Sau khi qua sông thì đi ngang được, nhưng KHÔNG BAO GIỜ lùi.',
    l1:'Hết nước đi là THUA, không có hoà vì hết nước như cờ vua.',
    l2:'Chiếu liên tục là THUA cho bên chiếu. Đây là khác biệt lớn nhất với cờ vua.',
    l3:'Lặp lại thế cờ 3 lần mà không ai chiếu liên tục thì HOÀ.',
    l4:'120 nước không ăn quân nào thì HOÀ.',
    l5:'Hai tướng không được nhìn thẳng nhau qua cột trống — gọi là "tướng đối mặt".',
    bi_an:'Quân bị ăn', giai_thich_muc:'Thời gian máy nghĩ mỗi nước',
    khong_co:'chưa ăn quân nào',
    ten:'Tiếng Việt', tieu_de:'Bàn phân tích', phu:'thang 0–1000 cho Đỏ',
    can_bang:'Cân bằng', do_loi:'Đỏ ưu thế', den_loi:'Đen ưu thế',
    do_thang:'Đỏ thắng', den_thang:'Đen thắng',
    nuoc_tot:'Nước tốt nhất cho', bien_chinh:'biến chính',
    neu_di:'nếu đi', diem_thanh:'điểm thành', nuoc_vua_di:'Nước vừa đi',
    theo_sach:'Theo sách', luong_gia:'lượng giá', tinh:'tĩnh', sau:'sâu',
    do_sau:'độ sâu', so_nut:'số nút', thoi_gian:'thời gian', nut_giay:'nút/s',
    may:'Máy', muc_do:'Mức độ', ben_cam:'Bạn cầm',
    de:'Dễ — 0,5 giây', vua:'Vừa — 3 giây', kho:'Khó — 10 giây',
    do:'Đỏ (đi trước)', den:'Đen (đi sau)',
    choi_may:'Chơi với máy', tu_choi:'Tự chơi hai bên',
    lui:'Lùi', van_moi:'Ván mới', xoay:'Xoay', di_goi_y:'Đi nước gợi ý',
    nuoc_da_di:'Nước đã đi',
    den_luot:'Đến lượt bạn', may_nghi:'Máy đang nghĩ…',
    dang_phan_tich:'Đang phân tích…', bi_chieu:'đang bị chiếu!',
    ban_thang:'Bạn thắng!', may_thang:'Máy thắng', hoa:'Hoà',
    tot:'Tốt', khong_chuan:'Không chuẩn', sai_lam:'Sai lầm',
    sai_nghiem:'Sai nghiêm trọng', chat_luong:'Nước vừa đi',
    chia_se:'Máy khác vào bằng', luot_cua:'Đến lượt',
    tong_ket:'Tổng kết ván', ho_nang_nhat:'Nước hớ nặng nhất',
    khong_ho:'không có nước hớ nào', so_nuoc_ngan:'nước',
    huy:'Huỷ', bat_dau:'Bắt đầu',
    chia_se_local:'Thiết bị Apple khác',
    lich_su:'Lịch sử ván đấu', dong:'Đóng', xem_lai:'Xem lại', xoa:'Xoá',
    chua_co_van:'Chưa có ván nào được lưu',
    ten_cua_ban:'Tên của bạn (để lưu ván)',
    thang_tu:'thắng', thua_tu:'thua', van_tu:'ván', xem_lai_van:'Đang xem lại ván',
    truoc_tu:'Trước', sau_tu:'Sau', thoat_xem_lai:'Thoát xem lại',
    luu_van_dau:'Lưu ván đấu', tai_van_dau:'Tải ván đấu',
  },
  en: {
    mui_ten:'Arrow', bat:'on', tat:'off',
    cach_ghi:'Move notation', vd:'Examples',
    g_tan:'+ (advance)', g_thoai:'- (retreat)', g_binh:'= (traverse)',
    g_tan_t:'Move toward the opponent. The number after is the NUMBER OF STEPS for straight movers, or the DESTINATION FILE for horse, elephant and advisor.',
    g_thoai_t:'Move back toward your own side. Numbering works the same as advance.',
    g_binh_t:'Move sideways. The number after is always the DESTINATION FILE.',
    g_cot:'Files are numbered from each side\'s own view: Red counts right to left, Black counts left to right. So the same file has two different numbers.',
    vd1:'C2=5 — the cannon on file 2 moves across to file 5',
    vd2:'N8+7 — the horse on file 8 advances, landing on file 7',
    vd3:'R1-2 — the chariot on file 1 retreats 2 steps',
    do_:'Red', den_:'Black', chua_di:'no move yet',
    l6:'Advisors and the General may never leave the 9-point palace.',
    l7:'A soldier before the river moves straight forward only — no sideways, no retreat.',
    l8:'A cannon moves like a chariot, but capturing requires exactly one piece as a screen.',
    l9:'There is no castling, no en passant and no promotion as in chess.',
    goi_y:'Show best move', ky_hieu:'character on piece', ghi_nuoc:'move notation', ten_quan:'Piece name',
    luat:'Rules', cach_di:'How pieces move', luat_dac_biet:'Special rules',
    quan:'Piece', di_the_nao:'Movement',
    q_K:'One step orthogonally, inside the 9-point palace only. May never face the enemy general down an open file.',
    q_A:'One step diagonally, inside the palace only. Stays beside the general as a shield.',
    q_E:'Two steps diagonally. May NOT cross the river. Blocked if the midpoint is occupied.',
    q_H:'One step then two, or two then one. Blocked if the square beside it along the long leg is occupied.',
    q_R:'Any distance orthogonally, as long as nothing blocks the path.',
    q_C:'Moves like a rook. But to CAPTURE it must jump over EXACTLY ONE piece.',
    q_P:'One step forward. After crossing the river it may also move sideways, but NEVER backwards.',
    l1:'Having no legal move is a LOSS — there is no stalemate draw as in chess.',
    l2:'Perpetual check is a LOSS for the checking side. This is the biggest difference from chess.',
    l3:'The same position three times, with no perpetual check, is a DRAW.',
    l4:'120 moves with no capture is a DRAW.',
    l5:'The two generals may never face each other down an open file.',
    bi_an:'Captured', giai_thich_muc:'Thinking time per move',
    khong_co:'none captured yet',
    ten:'English', tieu_de:'Analysis board', phu:'0–1000 scale for Red',
    can_bang:'Balanced', do_loi:'Red is better', den_loi:'Black is better',
    do_thang:'Red wins', den_thang:'Black wins',
    nuoc_tot:'Best move for', bien_chinh:'main line',
    neu_di:'if played', diem_thanh:'score becomes', nuoc_vua_di:'Last move',
    theo_sach:'From book', luong_gia:'evaluator', tinh:'static', sau:'deep',
    do_sau:'depth', so_nut:'nodes', thoi_gian:'time', nut_giay:'nodes/s',
    may:'Engine', muc_do:'Level', ben_cam:'You play',
    de:'Easy — 0.5 s', vua:'Normal — 3 s', kho:'Hard — 10 s',
    do:'Red (first)', den:'Black (second)',
    choi_may:'Play the engine', tu_choi:'Play both sides',
    lui:'Undo', van_moi:'New game', xoay:'Flip', di_goi_y:'Play best move',
    nuoc_da_di:'Moves',
    den_luot:'Your turn', may_nghi:'Engine thinking…',
    dang_phan_tich:'Analysing…', bi_chieu:'in check!',
    ban_thang:'You win!', may_thang:'Engine wins', hoa:'Draw',
    tot:'Good', khong_chuan:'Inaccuracy', sai_lam:'Mistake',
    sai_nghiem:'Blunder', chat_luong:'Last move',
    chia_se:'Other devices', luot_cua:'Turn',
    tong_ket:'Game review', ho_nang_nhat:'Biggest blunder',
    khong_ho:'no blunders', so_nuoc_ngan:'move',
    huy:'Cancel', bat_dau:'Start',
    chia_se_local:'Other Apple devices',
    lich_su:'Game history', dong:'Close', xem_lai:'Review', xoa:'Delete',
    chua_co_van:'No saved games yet',
    ten_cua_ban:'Your name (for saving games)',
    thang_tu:'won', thua_tu:'lost', van_tu:'games', xem_lai_van:'Reviewing game',
    truoc_tu:'Previous', sau_tu:'Next', thoat_xem_lai:'Exit review',
    luu_van_dau:'Save game', tai_van_dau:'Load game',
  },
  zh: {
    mui_ten:'箭头', bat:'开', tat:'关',
    cach_ghi:'着法记号', vd:'例子',
    g_tan:'进', g_thoai:'退', g_binh:'平',
    g_tan_t:'向对方前进。后面的数字：直行子为步数，马、象、士为目标纵线。',
    g_thoai_t:'向己方后退。数字用法同「进」。',
    g_binh_t:'横向移动。后面的数字永远是目标纵线。',
    g_cot:'纵线从各方自己一侧计数：红方自右向左，黑方自左向右。同一条线两方号码不同。',
    vd1:'炮二平五 — 二路炮横移到五路',
    vd2:'馬八進七 — 八路马前进，落到七路',
    vd3:'車一退二 — 一路车后退两步',
    do_:'红', den_:'黑', chua_di:'尚未走子',
    l6:'士和将帅不得离开九宫。',
    l7:'未过河的兵卒只能直进，不能横走，不能后退。',
    l8:'炮的走法同车，但吃子必须隔一个棋子作炮架。',
    l9:'没有王车易位、吃过路兵和升变。',
    goi_y:'提示着法', ky_hieu:'棋子上的字', ghi_nuoc:'着法记号', ten_quan:'棋子名称',
    luat:'规则', cach_di:'棋子走法', luat_dac_biet:'特殊规则',
    quan:'棋子', di_the_nao:'走法',
    q_K:'在九宫内直行一步。不得与对方将帅在同一直线上照面。',
    q_A:'在九宫内斜行一步，始终守护将帅。',
    q_E:'斜行两步（田字）。不可过河。田字中心有子则被塞象眼。',
    q_H:'走日字。长边相邻处有子则被蹩马腿。',
    q_R:'直行任意步数，路上不能有子阻挡。',
    q_C:'走法同车。但吃子必须隔一个棋子（炮架）。',
    q_P:'向前一步。过河后可横走，但永不后退。',
    l1:'无棋可走即判负，没有象棋中的逼和。',
    l2:'长将（连续将军）判负，这是与国际象棋最大的不同。',
    l3:'同一局面出现三次且无长将，判和。',
    l4:'120回合无吃子，判和。',
    l5:'双方将帅不得在同一直线上直接照面。',
    bi_an:'被吃棋子', giai_thich_muc:'每步思考时间',
    khong_co:'尚未吃子',
    ten:'中文', tieu_de:'分析板', phu:'红方 0–1000 分制',
    can_bang:'均势', do_loi:'红方优势', den_loi:'黑方优势',
    do_thang:'红方胜', den_thang:'黑方胜',
    nuoc_tot:'最佳着法', bien_chinh:'主要变例',
    neu_di:'若走', diem_thanh:'分数变为', nuoc_vua_di:'上一着',
    theo_sach:'来自开局库', luong_gia:'评估', tinh:'静态', sau:'深层',
    do_sau:'深度', so_nut:'节点', thoi_gian:'用时', nut_giay:'节点/秒',
    may:'引擎', muc_do:'难度', ben_cam:'你执',
    de:'简单 — 0.5 秒', vua:'普通 — 3 秒', kho:'困难 — 10 秒',
    do:'红方（先行）', den:'黑方（后行）',
    choi_may:'人机对弈', tu_choi:'双方自走',
    lui:'悔棋', van_moi:'新局', xoay:'翻转', di_goi_y:'走最佳着',
    nuoc_da_di:'着法',
    den_luot:'轮到你', may_nghi:'引擎思考中…',
    dang_phan_tich:'分析中…', bi_chieu:'被将军！',
    ban_thang:'你赢了！', may_thang:'引擎获胜', hoa:'和棋',
    tot:'好棋', khong_chuan:'不精确', sai_lam:'失误',
    sai_nghiem:'严重失误', chat_luong:'上一着',
    chia_se:'其他设备', luot_cua:'轮到',
    tong_ket:'对局复盘', ho_nang_nhat:'最大失误',
    khong_ho:'没有明显失误', so_nuoc_ngan:'着',
    huy:'取消', bat_dau:'开始',
    chia_se_local:'其他苹果设备',
    lich_su:'对局历史', dong:'关闭', xem_lai:'复盘', xoa:'删除',
    chua_co_van:'还没有保存的对局',
    ten_cua_ban:'你的名字（用于保存对局）',
    thang_tu:'胜', thua_tu:'负', van_tu:'局', xem_lai_van:'正在复盘',
    truoc_tu:'上一步', sau_tu:'下一步', thoat_xem_lai:'退出复盘',
    luu_van_dau:'保存对局', tai_van_dau:'载入对局',
  },
};
